Support DirEntry paths when checking is_fake_path
testing-cabal/systemfixtures pull request #9
Opened 2020-10-29 12:39 UTC by nessita

When using shutil.copytree from a non-overlayed dir to an overlayed dir,
copytree's implementation uses os.scandir that "returns an iterator of
os.DirEntry objects corresponding to the entries in the directory given
by path".

The os.DirEntry does not support calling startswith on it directly, so
this work handles that case by using it's name attribute instead.

2020-10-29 13:41 UTC, nessita commented
I will need to propose a slightly different patch because, while the Python documentation for `DirEntry` seems to imply it's available since Python 3.5 (https://docs.python.org/3/library/os.html#os.DirEntry), as explained in this bug https://bugs.python.org/issue28530, the `DirEntry` it's not exposed in the `os` module until 3.6.

The suggested workaround would be something along these lines:

```python

    import os

    try:
        from os import DirEntry
    except ImportError:
        import tempfile
        with tempfile.NamedTemporaryFile() as ftemp:
            scan = os.scandir(os.path.dirname(ftemp.name))
            DirEntry = type(next(scan))
        del scan, ftemp, tempfile
```

2022-10-18 12:45 UTC, jelmer commented
Python 3.5 is end of life - can you simplify this PR by dropping support for it?

2022-10-18 12:46 UTC, jelmer requested changes
Please propose travis

2022-10-18 12:46 UTC, jelmer commented on .travis.yml
> -  - "2.7"
Please leave this for a separate PR.

2022-10-18 12:46 UTC, jelmer commented on tox.ini
> +envlist = py27,py35,py36,py37,py38,py39
please do this in a separate PR

2022-10-18 19:19 UTC, jelmer approved these changes

2022-10-18 19:19 UTC, merged